import PendingApprovalsTable, { type PendingApproval } from "./loan-pending-approvals-table"

const awaitingMyApprovalData: PendingApproval[] = [
  { id: "1", applicationId: "LA-0000241", applicantName: "Juma Ali Said", loanType: "Personal Loan", loanTypeValue: "personal_loan", requestedAmount: "25,000,000", applicationDate: "May 14, 2024 09:35 AM", isoApplicationDate: "2024-05-14", loanOfficerName: "Salma Khamis", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "2", applicationId: "LA-0000243", applicantName: "Fatma Salim Rashid", loanType: "Personal Loan", loanTypeValue: "personal_loan", requestedAmount: "18,500,000", applicationDate: "May 14, 2024 10:15 AM", isoApplicationDate: "2024-05-14", loanOfficerName: "Salma Khamis", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "3", applicationId: "LA-0000247", applicantName: "Haruna Juma Mwinyi", loanType: "Business Loan", loanTypeValue: "business_loan", requestedAmount: "50,000,000", applicationDate: "May 14, 2024 11:02 AM", isoApplicationDate: "2024-05-14", loanOfficerName: "Abdul Karim", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "4", applicationId: "LA-0000251", applicantName: "Asha Hamis Suleiman", loanType: "Personal Loan", loanTypeValue: "personal_loan", requestedAmount: "15,000,000", applicationDate: "May 14, 2024 11:45 AM", isoApplicationDate: "2024-05-14", loanOfficerName: "Neema Lucas", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "5", applicationId: "LA-0000255", applicantName: "Mohamed Said Ally", loanType: "Business Loan", loanTypeValue: "business_loan", requestedAmount: "35,000,000", applicationDate: "May 14, 2024 12:10 PM", isoApplicationDate: "2024-05-14", loanOfficerName: "Abdul Karim", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "6", applicationId: "LA-0000258", applicantName: "Zainab Abdul Karim", loanType: "Personal Loan", loanTypeValue: "personal_loan", requestedAmount: "12,000,000", applicationDate: "May 14, 2024 12:35 PM", isoApplicationDate: "2024-05-14", loanOfficerName: "Salma Khamis", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "7", applicationId: "LA-0000260", applicantName: "Salum Abdallah Khatib", loanType: "Business Loan", loanTypeValue: "business_loan", requestedAmount: "40,000,000", applicationDate: "May 14, 2024 01:05 PM", isoApplicationDate: "2024-05-14", loanOfficerName: "Neema Lucas", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "8", applicationId: "LA-0000263", applicantName: "Neema Lucas Mollel", loanType: "Personal Loan", loanTypeValue: "personal_loan", requestedAmount: "20,000,000", applicationDate: "May 14, 2024 01:30 PM", isoApplicationDate: "2024-05-14", loanOfficerName: "Salma Khamis", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "9", applicationId: "LA-0000267", applicantName: "Yusuf Omari Mussa", loanType: "Emergency Loan", loanTypeValue: "emergency_loan", requestedAmount: "8,000,000", applicationDate: "May 14, 2024 02:05 PM", isoApplicationDate: "2024-05-14", loanOfficerName: "Herman Mushi", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "10", applicationId: "LA-0000271", applicantName: "Hassan Bakari Said", loanType: "Personal Loan", loanTypeValue: "personal_loan", requestedAmount: "22,500,000", applicationDate: "May 14, 2024 02:40 PM", isoApplicationDate: "2024-05-14", loanOfficerName: "Herman Mushi", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "11", applicationId: "LA-0000274", applicantName: "Amina Juma Rehani", loanType: "Business Loan", loanTypeValue: "business_loan", requestedAmount: "60,000,000", applicationDate: "May 14, 2024 03:15 PM", isoApplicationDate: "2024-05-14", loanOfficerName: "Abdul Karim", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
  { id: "12", applicationId: "LA-0000279", applicantName: "James Kileo Mramba", loanType: "Personal Loan", loanTypeValue: "personal_loan", requestedAmount: "17,000,000", applicationDate: "May 14, 2024 04:00 PM", isoApplicationDate: "2024-05-14", loanOfficerName: "Neema Lucas", approvalStepLabel: "Admin Approval", approvalStepNumber: 1, approvalStepTotal: 3, statusValue: "PENDING_APPROVAL" },
]

const AwaitingMyApprovalTable = () => {
  return <PendingApprovalsTable approvals={awaitingMyApprovalData} />
}

export default AwaitingMyApprovalTable
export { awaitingMyApprovalData }