import { Document, Page, Text, View, StyleSheet} from "@react-pdf/renderer"

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 9,
    fontFamily: "Helvetica",
    color: "#111111",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomWidth: 1,
    borderBottomColor: "#111111",
    paddingBottom: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
  },
  metaLabel: {
    fontFamily: "Helvetica-Bold",
  },
  metaRow: {
    flexDirection: "row",
    gap: 4,
    marginBottom: 2,
  },
  sectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  section: {
    marginBottom: 16,
  },
  card: {
    borderWidth: 1,
    borderColor: "#d9d9d9",
    borderRadius: 4,
    padding: 12,
  },
  twoCol: {
    flexDirection: "row",
    gap: 24,
  },
  col: {
    flex: 1,
  },
  fieldRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  fieldLabel: {
    width: 110,
    color: "#555555",
  },
  fieldColon: {
    width: 10,
  },
  fieldValue: {
    flex: 1,
    fontFamily: "Helvetica-Bold",
  },
  table: {
    borderWidth: 1,
    borderColor: "#d9d9d9",
    borderRadius: 4,
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#f5f5f5",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#d9d9d9",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
  },
  tableRowLast: {
    borderBottomWidth: 0,
  },
  tableColStep: { flex: 2, fontFamily: "Helvetica-Bold" },
  tableColStatus: { flex: 1 },
  tableColResult: { flex: 1 },
  tableHeaderText: {
    fontFamily: "Helvetica-Bold",
    color: "#555555",
  },
  passedText: {
    color: "#059669",
    fontFamily: "Helvetica-Bold",
  },
  threeCol: {
    flexDirection: "row",
    gap: 12,
  },
  miniCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d9d9d9",
    borderRadius: 4,
    padding: 10,
  },
  miniRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  miniLabel: {
    color: "#555555",
  },
  miniValue: {
    fontFamily: "Helvetica-Bold",
    textAlign: "right",
  },
  note: {
    marginTop: 6,
    color: "#555555",
    fontSize: 8,
  },
  finalStatus: {
    fontFamily: "Helvetica-Bold",
    color: "#059669",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 24,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#d9d9d9",
  },
  footerNote: {
    fontSize: 8,
    color: "#777777",
    maxWidth: 260,
    textAlign: "right",
  },
})

export type KycReportData = {
  reportId: string
  generatedOn: string
  generatedBy: string
  applicant: {
    name: string
    applicationId: string
    kycReferenceNo: string
    dateOfBirth: string
    gender: string
    phone: string
    email: string
    address: string
    nationality: string
    occupation: string
    maritalStatus: string
  }
  progress: { step: string; status: string; result: string }[]
  identificationDocuments: { type: string; status: string }[]
  nidaTin: {
    nidaNumber: string
    tinNumber: string
    verificationMethod: string
    verificationNotes: string
  }
  otp: {
    channel: string
    sentOn: string
    verifiedOn: string
    status: string
  }
  watchlist: { type: string; result: string; checkedOn: string }[]
  finalResult: {
    overallStatus: string
    result: string
    remarks: string
    expiryDate: string
  }
  verifiedBy: { name: string; role: string }
}

type KycReportDocumentProps = {
  data: KycReportData
}

const KycReportDocument = ({ data }: KycReportDocumentProps) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.headerRow}>
          <Text style={styles.title}>KYC VERIFICATION REPORT</Text>
          <View>
            <View style={styles.metaRow}>
              <Text style={styles.metaLabel}>Report ID:</Text>
              <Text>{data.reportId}</Text>
            </View>
            <View style={styles.metaRow}>
              <Text style={styles.metaLabel}>Generated On:</Text>
              <Text>{data.generatedOn}</Text>
            </View>
            <View style={styles.metaRow}>
              <Text style={styles.metaLabel}>Generated By:</Text>
              <Text>{data.generatedBy}</Text>
            </View>
          </View>
        </View>

        {/* Applicant Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>APPLICANT SUMMARY</Text>
          <View style={styles.twoCol}>
            <View style={styles.col}>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Applicant Name</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.name}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Application ID</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.applicationId}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>KYC Reference No.</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.kycReferenceNo}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Date of Birth</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.dateOfBirth}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Gender</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.gender}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Phone Number</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.phone}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Email Address</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.email}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Address</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.address}</Text>
              </View>
            </View>
            <View style={styles.col}>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Nationality</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.nationality}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Occupation</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.occupation}</Text>
              </View>
              <View style={styles.fieldRow}>
                <Text style={styles.fieldLabel}>Marital Status</Text>
                <Text style={styles.fieldColon}>:</Text>
                <Text style={styles.fieldValue}>{data.applicant.maritalStatus}</Text>
              </View>
            </View>
          </View>
        </View>

        {/* KYC Verification Progress */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>KYC VERIFICATION PROGRESS</Text>
          <View style={styles.table}>
            <View style={styles.tableHeaderRow}>
              <Text style={[styles.tableColStep, styles.tableHeaderText]}>Verification Step</Text>
              <Text style={[styles.tableColStatus, styles.tableHeaderText]}>Status</Text>
              <Text style={[styles.tableColResult, styles.tableHeaderText]}>Result</Text>
            </View>
                {data.progress.map((row, index) => {
                const isLastRow = index === data.progress.length - 1
                return (
                    <View
                    key={row.step}
                    style={isLastRow ? [styles.tableRow, styles.tableRowLast] : styles.tableRow}
                    >
                    <Text style={styles.tableColStep}>{row.step}</Text>
                    <Text style={styles.tableColStatus}>{row.status}</Text>
                    <Text style={[styles.tableColResult, styles.passedText]}>{row.result}</Text>
                    </View>
                )
                })}
          </View>
        </View>

        {/* Identification Documents / NIDA-TIN / OTP */}
        <View style={styles.section}>
          <View style={styles.threeCol}>
            <View style={styles.miniCard}>
              <Text style={styles.sectionTitle}>IDENTIFICATION DOCUMENTS</Text>
              {data.identificationDocuments.map((doc) => (
                <View key={doc.type} style={styles.miniRow}>
                  <Text style={styles.miniLabel}>{doc.type}</Text>
                  <Text style={styles.miniValue}>{doc.status}</Text>
                </View>
              ))}
              <Text style={styles.note}>All documents were reviewed and verified by authorized staff.</Text>
            </View>

            <View style={styles.miniCard}>
              <Text style={styles.sectionTitle}>NIDA / TIN VERIFICATION</Text>
              <View style={styles.miniRow}>
                <Text style={styles.miniLabel}>NIDA Number</Text>
                <Text style={styles.miniValue}>{data.nidaTin.nidaNumber}</Text>
              </View>
              <View style={styles.miniRow}>
                <Text style={styles.miniLabel}>TIN Number</Text>
                <Text style={styles.miniValue}>{data.nidaTin.tinNumber}</Text>
              </View>
              <View style={styles.miniRow}>
                <Text style={styles.miniLabel}>Verification Method</Text>
                <Text style={styles.miniValue}>{data.nidaTin.verificationMethod}</Text>
              </View>
              <Text style={styles.note}>{data.nidaTin.verificationNotes}</Text>
            </View>

            <View style={styles.miniCard}>
              <Text style={styles.sectionTitle}>OTP VERIFICATION</Text>
              <View style={styles.miniRow}>
                <Text style={styles.miniLabel}>Channel</Text>
                <Text style={styles.miniValue}>{data.otp.channel}</Text>
              </View>
              <View style={styles.miniRow}>
                <Text style={styles.miniLabel}>OTP Sent On</Text>
                <Text style={styles.miniValue}>{data.otp.sentOn}</Text>
              </View>
              <View style={styles.miniRow}>
                <Text style={styles.miniLabel}>OTP Verified On</Text>
                <Text style={styles.miniValue}>{data.otp.verifiedOn}</Text>
              </View>
              <Text style={styles.note}>OTP verification completed successfully.</Text>
            </View>
          </View>
        </View>

        {/* Watchlist Screening / Final KYC Result */}
        <View style={styles.section}>
          <View style={styles.twoCol}>
            <View style={styles.miniCard}>
              <Text style={styles.sectionTitle}>WATCHLIST SCREENING</Text>
              {data.watchlist.map((row) => (
                <View key={row.type} style={styles.miniRow}>
                  <Text style={styles.miniLabel}>{row.type}</Text>
                  <Text style={styles.miniValue}>{row.result}</Text>
                </View>
              ))}
              <Text style={styles.note}>No adverse records found in watchlist screening.</Text>
            </View>

            <View style={styles.miniCard}>
              <Text style={styles.sectionTitle}>FINAL KYC RESULT</Text>
              <View style={styles.miniRow}>
                <Text style={styles.miniLabel}>Overall Status</Text>
                <Text style={styles.finalStatus}>{data.finalResult.overallStatus}</Text>
              </View>
              <Text style={{ marginBottom: 6 }}>{data.finalResult.result}</Text>
              <Text style={styles.note}>{data.finalResult.remarks}</Text>
              <View style={[styles.miniRow, { marginTop: 6 }]}>
                <Text style={styles.miniLabel}>KYC Expiry Date</Text>
                <Text style={styles.miniValue}>{data.finalResult.expiryDate}</Text>
              </View>
            </View>
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footerRow}>
          <View>
            <Text style={styles.fieldValue}>{data.verifiedBy.name}</Text>
            <Text style={styles.miniLabel}>{data.verifiedBy.role}</Text>
          </View>
          <Text style={styles.footerNote}>
            This is a system generated report and does not require a physical signature. Please keep this report
            confidential and secure.
          </Text>
        </View>
      </Page>
    </Document>
  )
}

export default KycReportDocument